FROM maven:3.8.3-openjdk-17

COPY . /opt/
WORKDIR /opt

RUN rm -f src/main/resources/application.properties && \
    cp application.properties src/main/resources/application.properties && \
    mvn clean package -DskipTests

WORKDIR /opt/target
EXPOSE 8081

CMD ["java","-jar","student-registration-backend-0.0.1-SNAPSHOT.jar"]
